PRAGMA foreign_keys = ON;

-- Initial Phase 4A live evidence seed.
-- Each INSERT is guarded by both the production Series Hub ID and the stable TMDB ID.
-- The evidence_key values are the exact SHA-256 fingerprints generated by
-- src/lifecycle.js for the same editorial payloads, so a later workflow upsert
-- of the same evidence is idempotent rather than duplicative.

-- Silo — Apple TV Press, 2024-12-16.
INSERT OR IGNORE INTO lifecycle_events (
  evidence_key, show_id, season_id, season_number, event_type, source_id,
  source_url, source_title, source_published_at, confidence, evidence_note
)
SELECT
  'ac00ae9c7010ee5953824e6a7fc9116c359bf31250fd2989eb764621d7421112',
  s.id,
  (SELECT se.id FROM seasons se WHERE se.show_id = s.id AND se.season_number = 3 LIMIT 1),
  3,
  'renewed',
  (SELECT id FROM sources WHERE source_key = 'apple_tv_press' LIMIT 1),
  'https://www.apple.com/tv-pr/news/2024/12/apple-tv-renews-hit-world-building-drama-silo-for-seasons-three-and-four/',
  'Apple TV+ renews hit, world-building drama “Silo” for seasons three and four',
  '2024-12-16',
  'official',
  'Apple announced renewal through season three.'
FROM shows s
WHERE s.id = 4 AND s.tmdb_id = 125988;

INSERT OR IGNORE INTO lifecycle_events (
  evidence_key, show_id, season_id, season_number, event_type, source_id,
  source_url, source_title, source_published_at, confidence, evidence_note
)
SELECT
  '5ab203c34a572aa0c0b87f61ccf147113994f24c3ab505bb2b536e1d964fc982',
  s.id,
  (SELECT se.id FROM seasons se WHERE se.show_id = s.id AND se.season_number = 4 LIMIT 1),
  4,
  'renewed',
  (SELECT id FROM sources WHERE source_key = 'apple_tv_press' LIMIT 1),
  'https://www.apple.com/tv-pr/news/2024/12/apple-tv-renews-hit-world-building-drama-silo-for-seasons-three-and-four/',
  'Apple TV+ renews hit, world-building drama “Silo” for seasons three and four',
  '2024-12-16',
  'official',
  'Apple announced renewal through season four.'
FROM shows s
WHERE s.id = 4 AND s.tmdb_id = 125988;

INSERT OR IGNORE INTO lifecycle_events (
  evidence_key, show_id, season_id, season_number, event_type, source_id,
  source_url, source_title, source_published_at, confidence, evidence_note
)
SELECT
  'f16d5eeecd10bae46c4c4ca28ff9bd9f396a2653929177d8d217ac3f570e9b64',
  s.id,
  (SELECT se.id FROM seasons se WHERE se.show_id = s.id AND se.season_number = 4 LIMIT 1),
  4,
  'final_season',
  (SELECT id FROM sources WHERE source_key = 'apple_tv_press' LIMIT 1),
  'https://www.apple.com/tv-pr/news/2024/12/apple-tv-renews-hit-world-building-drama-silo-for-seasons-three-and-four/',
  'Apple TV+ renews hit, world-building drama “Silo” for seasons three and four',
  '2024-12-16',
  'official',
  'Apple identified season four as the final season.'
FROM shows s
WHERE s.id = 4 AND s.tmdb_id = 125988;

-- For All Mankind — Apple TV Press, 2026-03-24.
INSERT OR IGNORE INTO lifecycle_events (
  evidence_key, show_id, season_id, season_number, event_type, source_id,
  source_url, source_title, source_published_at, confidence, evidence_note
)
SELECT
  'ebe4b71b747844ff4618e59ac1f95e14a7d7ef9a3c1db89bf58b3aed7df2b807',
  s.id,
  (SELECT se.id FROM seasons se WHERE se.show_id = s.id AND se.season_number = 6 LIMIT 1),
  6,
  'renewed',
  (SELECT id FROM sources WHERE source_key = 'apple_tv_press' LIMIT 1),
  'https://www.apple.com/tv-pr/news/2026/03/apple-tv-renews-award-winning-and-globally-acclaimed-space-drama-for-all-mankind-for-sixth-and-final-season/',
  'Apple TV renews “For All Mankind” for sixth and final season',
  '2026-03-24',
  'official',
  'Apple announced renewal for season six.'
FROM shows s
WHERE s.id = 58 AND s.tmdb_id = 87917;

INSERT OR IGNORE INTO lifecycle_events (
  evidence_key, show_id, season_id, season_number, event_type, source_id,
  source_url, source_title, source_published_at, confidence, evidence_note
)
SELECT
  'ea0d5811871bcfb710a617829a5e3ddf1f49c1953f441da722ad4f777b9f6e54',
  s.id,
  (SELECT se.id FROM seasons se WHERE se.show_id = s.id AND se.season_number = 6 LIMIT 1),
  6,
  'final_season',
  (SELECT id FROM sources WHERE source_key = 'apple_tv_press' LIMIT 1),
  'https://www.apple.com/tv-pr/news/2026/03/apple-tv-renews-award-winning-and-globally-acclaimed-space-drama-for-all-mankind-for-sixth-and-final-season/',
  'Apple TV renews “For All Mankind” for sixth and final season',
  '2026-03-24',
  'official',
  'Apple identified season six as the final season.'
FROM shows s
WHERE s.id = 58 AND s.tmdb_id = 87917;

INSERT OR IGNORE INTO lifecycle_events (
  evidence_key, show_id, season_id, season_number, event_type, source_id,
  source_url, source_title, source_published_at, confidence, evidence_note
)
SELECT
  '6d8cdcb8833b61fc99a0f3c6384a5c4b02d2d4254fe67c1b88b64e3e36f4dcbd',
  s.id,
  (SELECT se.id FROM seasons se WHERE se.show_id = s.id AND se.season_number = 6 LIMIT 1),
  6,
  'pre_production',
  (SELECT id FROM sources WHERE source_key = 'apple_tv_press' LIMIT 1),
  'https://www.apple.com/tv-pr/news/2026/03/apple-tv-renews-award-winning-and-globally-acclaimed-space-drama-for-all-mankind-for-sixth-and-final-season/',
  'Apple TV renews “For All Mankind” for sixth and final season',
  '2026-03-24',
  'official',
  'Apple stated the sixth season was about to enter production.'
FROM shows s
WHERE s.id = 58 AND s.tmdb_id = 87917;
